# Generated by Django 5.2 on 2025-04-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='companion_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail do Acompanhante'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
